services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet
    ports:
      - "5439:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
